global:
  marketplace-ami: false
  owner: sshvans@amazon.com
  qsname: quickstart-datalake-cloudwick
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true

tests:
  quickstart-data-lake-cloudwickt1:
    parameter_input: qs-datalake-defaults.json
    template_file: datalake-master.template
    regions:
    - us-east-1
    - us-west-2
    - eu-west-1